services:
  postgres:
    image: postgres:latest
    container_name: resourceservice_postgresql
    restart: always
    environment:
      - POSTGRES_PASSWORD=prueba123
      - POSTGRES_USER=user
      - POSTGRES_DB=resourceservicedb
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - ./postgresql/database/data:/var/lib/postgresql/data
